// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package myfirstmodule.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import myfirstmodule.imp.MySpringBootApplication;
import myfirstmodule.imp.MySpringService;
import org.springframework.web.servlet.MyRequestHandler;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;

public class Java_action extends CustomJavaAction<java.lang.Void>
{
	public Java_action(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		MySpringBootApplication.start();

		// 运行应用
		var service = MySpringBootApplication.ctx.getBean(MySpringService.class).doSomething();
		this._logNode.info(service != null ? "Success" : "Failure");
		Core.addRequestHandler("api", new MyRequestHandler());
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Java_action";
	}

	// BEGIN EXTRA CODE
	private ILogNode _logNode = Core.getLogger(Java_action.class.getName());
	// END EXTRA CODE
}
